dist: trusty
# Full VM image as the containers don't allow creating user namespaces.
sudo: required
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
script:
  - pip3 install .
  - runjail true
  - ./test.py
notifications:
  email: false
